# Ansible adhoc commands

---
- name: "Ping Servers"
  hosts: all
  tasks:
    - ping:

# Execute playbook
ansible-playbook playbook.yml

# Run "ping" module (-m) for "all" hosts
ansible -m ping all

# Run a command for all hosts
ansible -a 'cat /etc/hosts' all

ansible --version

ansible -m setup localhost

ansible -m ping localhost

ansible -i /home/thor/playbooks/inventory -m ping all

ansible -a 'date' -i /home/thor/playbooks/inventory web1

# Shell Script Example
#shell-script.sh
export ANSIBLE_GATHERING=explicit
ansible -m ping all
ansible -a 'cat /etc/hosts' all
ansible-playbook playbook.yml

sh shell-script.sh

chmod 755 shell-script.sh
./shell-script.sh

# Scripts Lab
#~/playbooks/host_details.sh
ansible all -a 'cat /etc/hostname' -i inventory
ansible node00 -m copy -a "src=/etc/resolv.conf dest=/tmp/resolve.conf" -i inventory

# Scripts Lab2
#~/playbooks/playbook.yml
---
- name: "Display /etc/redhat-release for all inventory"
  hosts: all
  tasks:
  - name: "cat /etc/redhat-release"
    command: cat /etc/redhat-release

#~/playbooks/host_data.sh
export ANSIBLE_GATHERING=explicit
ansible all -a 'uptime' -i inventory
ansible-playbook -i inventory -vv playbook.yml

